# Generated by Django 2.2 on 2019-05-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('carnet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('codigo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materias_X_Estudiante',
            fields=[
                ('id_materia_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Estudiante')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Materias')),
            ],
        ),
    ]
